### ISSUE TITLE
Add optional command line flag to use other resolvers

### ISSUE THREAD

**Issue by ghost** [pforemski/dingo#1]
It would be great to have an optional command line flag to specify a HTTPS revolver other than Google's

**Comment by pforemski** [comment]
Which resolvers other than Google, for example? They would need to implement the same API. I am not aware of any existing.

**Comment by ghost** [comment]
@pforemski In this case it would be my own resolver implementation. I am also unaware of any other public resolvers, but others may add support after Google finalizes the spec. At any rate, it should be a trivial modification.

**Comment by ghost** [comment]
@pforemski If I'm not mistaken, the only think that would need to be added is a optional flag that affects hreq.Host in line #180.

**Comment by pforemski** [comment]
Thanks for your suggestion but I don't see it is practical. That is, I don't see a reason someone should implement the Google API. Instead, I'd rather allow the resolver function to implement various APIs, e.g. https://www.openresolve.com/ - or your own, if you decide to do so.
