### ISSUE TITLE
OpenDNS error: "http2: could not negotiate protocol mutually"

### ISSUE THREAD

**Issue by kkovacs** [pforemski/dingo#22]
Hi Pawel,

Lately OpenDNS seems to give an error (latest version of code):

> $ ./dingo -port=53 -odns:workers=10 -gdns:workers=0
> 2017/01/05 14:29:40 starting 10 OpenDNS client(s) querying server 67.215.70.81
> 2017/01/05 14:29:40 dingo ver. 0.13 listening on 127.0.0.1 UDP port 53
> 2017/01/05 14:29:43 resolving index.hu./A
> 2017/01/05 14:29:43 http.Do(): Get https://67.215.70.81/A/index.hu.: http2: could not negotiate protocol mutually

Google works all right.

Also, thanks for the great software, keep up the good work!

**Comment by pforemski** [comment]
Hi Kristóf,

Thanks for using dingo. For OpenDNS, you need to start dingo with the `-h1` option that switches back to HTTP/1.1 mode. Unfortunately, www.openresolve.com doesn't support HTTP2 (yet?).

**Comment by kkovacs** [comment]
Thank you for the answer, Pawel!

Do you think there would be value in downgrading the HTTP automatically (silently or not) if the user choose to use Odns?

**Comment by pforemski** [comment]
implemented in https://github.com/pforemski/dingo/commit/42078d501f78b2c2ed471fd855eb3a824d8725f3 :)

**Comment by kkovacs** [comment]
Great, thanks, Pawel! :)
