### ISSUE TITLE
compile error...

### ISSUE THREAD

**Issue by jzp820927** [pforemski/dingo#27]
go version: go1.9beta2 linux/amd64
quic-go: Latest commit 3157e2d

Error log:
go get -u github.com/pforemski/dingo
# github.com/pforemski/dingo
../src/github.com/pforemski/dingo/https.go:39:15: undefined: h2quic.QuicRoundTripper

**Comment by ghost** [comment]
you have to edit https.go and change h2quic.QuicRoundTripper to h2quic.RoundTripper

**Comment by pforemski** [comment]
Fixed in master, thanks @GinoM

**Comment by jzp820927** [comment]
thanks.

**Comment by gripedthumbtacks** [comment]
still seems broken in master

https.go:39: undefined: h2quic.RoundTripper
