### ISSUE TITLE
dingo actually uses HTTP/2.0 already?

### ISSUE THREAD

**Issue by ghost** [pforemski/dingo#3]
I don't have much experience with golang, but I just read the following on the net/http2 docs: [This package is low-level and intended to be used directly by very few people. Most users will use it indirectly through the automatic use by the net/http package (from Go 1.6 and later).](https://godoc.org/golang.org/x/net/http2)

Also see the following (bottom of page): [The http package has transparent support for the HTTP/2 protocol when using HTTPS.](https://golang.org/pkg/net/http/)

**Comment by pforemski** [comment]
Unfortunately, it doesn't, as Go 1.6+ will use HTTP/2 only if you don't touch the TLS options, i.e. use the default HTTP transport (which is not the case for dingo).
