### ISSUE TITLE
https.go:39: undefined: h2quic.RoundTripper

### ISSUE THREAD

**Issue by gripedthumbtacks** [pforemski/dingo#37]
still seems broken in master

https.go:39: undefined: h2quic.RoundTripper

**Comment by heri16** [comment]
You have an outdated src for quic-go. Fix: `go get -u github.com/lucas-clemente/quic-go`

**Comment by gripedthumbtacks** [comment]
probably fixed in the last couple months since posting. closing.

**Comment by gripedthumbtacks** [comment]
welp

# github.com/lucas-clemente/quic-go
go/src/github.com/lucas-clemente/quic-go/interface.go:14: syntax error: unexpected = in type declaration
go/src/github.com/lucas-clemente/quic-go/interface.go:17: syntax error: unexpected = in type declaration
go/src/github.com/lucas-clemente/quic-go/interface.go:20: syntax error: unexpected = in type declaration

**Comment by gripedthumbtacks** [comment]
upstream appears to have fixed this now. closing.
