### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by pforemski** [pforemski/dingo#7]
Go supports H/2 natively, but only if we don't touch the defaults, which isn't the case: dingo spoofs the SNI string in TLS handshakes, which is why Go selects the HTTP/1.1 transport instead of HTTP/2.

**Comment by voidd** [comment]
https://github.com/golang/go/issues/16581#issuecomment-239902775
I think it would be good idea to enable HTTP/2 by default. With importing golang.org/x/net/http2 as external dependency.
#19

**Comment by pforemski** [comment]
Thanks, implemented in https://github.com/pforemski/dingo/commit/91bb369d383ecd9ccc6d04ff4cfd12414c4d65dd
